### ISSUE TITLE
Is a Win64 version possible?

### ISSUE THREAD

**Issue by RaXaR** [sirikata/berkelium#21]
Hi as the title states, I was wondering if a a Win64 version is possible? I did read somewhere that in fact the chrome side of things are still 32bit only but I'm not sure if that is still the case. Thanks for any info.

**Comment by ewencp** [comment]
This still seems to be the case with Chromium, but even if it weren't we're _very_ far behind Chromium's HEAD. No Win64 version is going to come anytime soon.
