### ISSUE TITLE
can't make tests

### ISSUE THREAD

**Issue by jarrettchisholm** [sirikata/berkelium#22]
When compiling the berkelium library (using `make`), the following error occurs:

```
/usr/bin/python: can't open file '/home/jarrett/projects/berkelium/externals/cxxtest/cxxtestgen.py': [Errno 2] No such file or directory
make[2]: *** [cxxtest_tests.cc] Error 2
make[1]: *** [CMakeFiles/tests.dir/all] Error 2
make: *** [all] Error 2
```

Looks like the `cxxtest` folder has nothing in it.  On github it looks like it 'links' to another project...

**Comment by ewencp** [comment]
You need to run

```
git submodule update --init --recursive
```

from the Berkelium directory to get the code for cxxtest.
