### ISSUE TITLE
berkelium doesn't build on raspbian ( raspberry pi hardfp )

### ISSUE THREAD

**Issue by hellbender3069** [sirikata/berkelium#24]
I am working on getting berkelium and chromium compiled for the raspberry pi, but I run into two problems.
1. With using ./util/build_chromium it halts when the gyp script has to run an external shell script. for example when it is trying to find the architecture of python. It says the script exited with exit status 0 ( which i think is good ) but the process exits on it. When I go into the chromium src directory and run 'make' everything runs fine. I experienced this same problem when checking out the latest chromium and trying to build that. Once again all shell scripts made the process fail.
2. the cxxtests won't build because it can't find sources. After i patched the common.gypi to hardcoded select arm as the architecture, chromium and berkelium build. But the cxx tests never build so i have to comment them out of the files to get the build process to finish.

I will add the failure texts to this issue as soon as I get them ( building an a raspberry pi natively is a waiting game, but it works ) for clearer information

**Comment by ewencp** [comment]
On the two issues:
1. An exit status of 0 means "completed successfully", but if this is an external script run by gyp, it could be checking that something _fails_ and that 0 exit status could be a bad thing. But without any more information about where it's failing I can't really suggest anything to look into. I don't have a Raspberry PI, so I don't have a way of looking into this more myself.
2. You almost definitely just forgot to run the git submodule command mentioned in the README.txt.

I'm surprised you managed to get it building on the Raspberry PI -- don't they only have 512MB of RAM maximum? Normally that would make it take forever to link because it'd end up using a lot of swap space.

**Comment by hellbender3069** [comment]
I removed everything and will restart from scratch. When i get the error message I will post it here. 

I set up the RPi with a 16Gb flash and created 1,5Gb of swap in addition to the 512Mb internal mem. It does the jobm but takes about 48 hours to complete. Not really fast but certainly more stable than all those cross compile solutions. And as long as I don't have to look at the whole compiling let it run.

By the way I changed the libjpeg_turbo to a higher revision so it will compile on ARM. ( And if all goes well I will try compiling against the latest green waterfall of chromium )

**Comment by ewencp** [comment]
Ok, so apparently the combination of the weaker CPU and having to swap a lot makes it take about 50x longer to build...

The latest green waterfall chromium will definitely not work. Berkelium is very sensitive to changes to the Chromium code since it is essentially a replacement for Chromium's main() which ties all the components together. It may build with other chromium11 versions, but definitely doesn't build with chromium12 or higher. Just want to make sure you know this since one experiment with a new version will apparently take 2 days :)

**Comment by hellbender3069** [comment]
Alright I got it compiled. Because of the fact that Berkelium works on Chrome 11 I had to update some dependencies on chrome to build the all. Especially libjpeg-turbo needed upgrading because a newer version of it supports ARM architecture. Luckely it didn't break the interface. So now i got a working chromium 11 and a hopefully working berkelium. I did use 'make test' but it only ran 1 test as far as i can see, a blanking test of some sort. At the first time chromium crashed with an error, but all the following times it passed the test. I presume it had something to do with retrieving a certificate which took too long. 

Now I am going on and try to build libbrowsernode from it. This will be a complete different challenge since it was build against libavg 1.6 and only libavg 1.7 is RPi compatible. But those issues are for another forum.

Thanks for all the help

**Comment by ewencp** [comment]
Great, glad to hear it finally got built. Any chance you could contribute back a patch that gets it building? Obviously it would't be applied by default but we could either apply it selectively in build-chromium.sh or even just include it and reference it in the README. I'd love it if it was easier for others to get it build on RaspberryPI in the future.

And good luck with getting the libraries you're _really_ trying to use to build!

**Comment by hellbender3069** [comment]
Hi Ewen,
Well it is not as much the use of a patch that will do anything, except for changing the revision of libjpeg-turbo. It is more about using the correct settings. 

in ~/.gyp/include.gypi I placed the following :

{
'variables': {
'target_arch': 'arm',
'disable_nacl': 1,  # NaCL does not build for ARM.
'linux_use_tcmalloc': 0, # tcmalloc does not build for ARM.
'armv7': 0, # Optional, for targeting ARMv7.
'armv6': 1, # Optional, for targeting ARMv7.
'arm_thumb': 0, # Optional, for targeting thumb.  Combine with armv7 to target $
'arm_neon': 0, # Optional, to disable NEON. 1 is the default, and most people w$
'arm_fpu': 'vfp', # Optional, to select which version of vfp to use if NEON is $
'verbose': 1,
'use_system_yasm': 0
}
}

The last option about Yasm is especially for the latest version of libjpeg-turbo.

My enviroment variables for the build were :

export CROSSTOOL=arm-linux-gnueabihf
export CXX=$CROSSTOOL-g++
export CC=$CROSSTOOL-gcc
export AR=$CROSSTOOL-ar
export AS=$CROSSTOOL-as
export RANLIB=$CROSSTOOL-ranlib
export CFLAGS="-I/usr/include/gtk-2.0 -I/usr/include/glib-2.0 -march=armv6 -mfpu=vfp -mfloat-abi=hard"
export CCFLAGS=$CFLAGS
export CXXFLAGS="-I/usr/include/gtk-2.0 -I/usr/include/glib-2.0/ -I/usr/lib/glib-2.0/include/ -I/usr/include/pango-1.0 -I/usr/include/cairo/ -I/usr/include/librsvg-2 -O3  -march=armv6 -mfpu=vfp -mfloat-abi=hard"
export GYP_DEFINES="target_arch=arm disable_nacl=1 linux_use_tcmalloc=0 armv6=1 arm_thumb=0 use_libjpeg_turbo=1"

Because I still use the crosstool commandlines ( which shouldn't be really needed since I build natively ) I had to symlink ar and ran to arm-linux-gnueabihf-ar and arm-Linux-gnueabihf-ran

After downloading chromium it starts building and failes with libjpeg-turbo. At that point I changed ./build/chromium/11.0.696.77/DEPS so libjpeg-turbo was fetched at revision 177737

   'src/third_party/libjpeg_turbo':
      '/trunk/deps/third_party/libjpeg_turbo@177737',

After that all build as expected ( when I downloaded about 150 extra dependencies :-) but those are all easy to spot if you mis them, most compiler and linker errors are easy enough to resolve.
